const glowColor = 'rgba(59, 130, 246, 0.2)';

export const shadow = `0 0 5px ${glowColor}, 0 0 10px ${glowColor}, 0 0 15px ${glowColor}, 0 0 20px ${glowColor}`;

export const themes = [
  'light',
  'dark',
  'green-velvet-light',
  'green-velvet-dark',
  'blue-coral-light',
  'blue-coral-dark',
  'fantastic-light',
  'fantastic-dark',
  'sw-pastel-light',
  'sw-pastel-dark',
  'fresh-mint-light',
  'fresh-mint-dark',
  'january-blue-crawdad-light',
  'january-blue-crawdad-dark',
  'goose-light',
  'goose-dark',
  'ocean-light',
  'ocean-dark',
  'unicscode-light',
  'unicscode-dark',
  'midnight-tokyo-light',
  'midnight-tokyo-dark',
  'purple-v2-light',
  'purple-v2-dark',
  'nepali-blue-light',
  'nepali-blue-dark',
  'coffee-light',
  'coffee-dark',
  'quokka-light',
  'quokka-dark',
  'earth-tones-light',
  'earth-tones-dark',
  'pastel-light',
  'pastel-dark',
  'pastel-2-light',
  'pastel-2-dark',
  'dark-matter-light',
  'dark-matter-dark',
  'dodger-blue-light',
  'dodger-blue-dark',
  'amnesia-blue-light',
  'amnesia-blue-dark',
  'lush-leaf-light',
  'lush-leaf-dark',
  'surf-light',
  'surf-dark',
  'wickford-light',
  'wickford-dark',
];
